[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.2"]

[project]
authors = [
  {name = "Edoardo Giussani", email = "egiussani@izsvenezie.it"},
  {name = "Alessandro Sartori", email = "asartori@izsvenezie.it"},
]
description = "A tool to search for molecular markers with potential impact on the biological characteristics of Influenza A viruses of the A(H5N1) subtype."
dynamic = ["version"]
keywords = ["flumut", "molecular markers", "Influenza A Virus", "AIV"]
license = "AGPL-3.0"
license-files = ["LICENSE"]
name = "flumut"

dependencies = [
  "click >=8.0.0",
  "biopython>=1.87",
  "openpyxl >= 3.1.2",
  "peewee>=4.0.5",
  "platformdirs>=4.9.6",
]
requires-python = ">=3.10"

[project.readme]
content-type = "text/markdown"
file = "README.md"

[project.urls]
"Bug Reports" = "https://github.com/izsvenezie-virology/FluMut/issues"
"Homepage" = "https://izsvenezie-virology.github.io/FluMut"
"Source" = "https://github.com/izsvenezie-virology/FluMut"

[project.scripts]
flumut = "flumut.cli:cli"

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*"]

[tool.setuptools.dynamic]
version = {attr = "flumut.__version__"}
