#!/usr/bin/env python3
"""Dump the FluMut database to a deterministic SQL file, so its changes are reviewable.

The binary stays the source of truth — the editor writes it and the package
loads it. This dump is a generated artifact kept beside it in git, and
``--check`` fails when the two have drifted apart.

Usage::

    python scripts/dump_db.py
"""

import argparse
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATABASE = ROOT / 'src' / 'flumut' / 'data' / 'flumut_db.sqlite'
DEFAULT_DUMP = ROOT / 'db' / 'flumut_db.sql'

HEADER = """\
-- FluMutDB v.{version} - Sorted dump for database diffs
--
-- Generated by scripts/dump_db.py. Do not edit by hand.
"""


def connect(database: Path) -> sqlite3.Connection:
    """Open ``database`` read-only."""
    if not database.is_file():
        raise FileNotFoundError(f'No database at {database}')
    return sqlite3.connect(f'file:{database}?mode=ro', uri=True)


def database_version(connection: sqlite3.Connection) -> str:
    """Return the FluMutDB version recorded in the database."""
    row = connection.execute('SELECT major, minor, patch FROM dbversion LIMIT 1').fetchone()
    return '.'.join(str(part) for part in row)


def table_names(connection: sqlite3.Connection) -> list[str]:
    """Every user table, in a stable alphabetical order."""
    rows = connection.execute("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    return [name for (name,) in rows]


def object_statements(connection: sqlite3.Connection, kind: str, table: str) -> list[str]:
    """The ``CREATE`` statements of every index, trigger or view belonging to ``table``."""
    rows = connection.execute(
        'SELECT sql FROM sqlite_master WHERE type = ? AND tbl_name = ? AND sql IS NOT NULL ORDER BY name',
        (kind, table),
    )
    return [sql for (sql,) in rows]


def column_names(connection: sqlite3.Connection, table: str) -> list[str]:
    """The columns of ``table``, in declaration order. Moves order and notes columns at the end if present."""
    result = [row[1] for row in connection.execute(f'PRAGMA table_info("{table}")')]
    result.append('order')
    result.remove('order')
    result.append('notes')
    result.remove('notes')
    return result


def insert_statements(connection: sqlite3.Connection, table: str) -> list[str]:
    """One ``INSERT`` per row, with values quoted by SQLite itself."""
    columns = column_names(connection, table)
    if not columns:
        return []

    quoted = ', '.join(f'CAST(quote("{column}") AS TEXT)' for column in columns)
    names = ', '.join(f'"{column}"' for column in columns)

    rows = connection.execute(f'SELECT {quoted} FROM "{table}" ORDER BY id')
    return [f'INSERT INTO "{table}" ({names}) VALUES ({", ".join(row)});' for row in rows]


def render(connection: sqlite3.Connection) -> str:
    """Render the whole database as SQL, one self-contained block per table."""
    lines = [HEADER.format(version=database_version(connection)), '', 'PRAGMA foreign_keys=OFF;', 'BEGIN TRANSACTION;']

    for table in table_names(connection):
        lines += ['', f'-- {"-" * 68}', f'-- {table}', f'-- {"-" * 68}', '']
        schema = connection.execute("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)).fetchone()
        if schema and schema[0]:
            lines.append(f'{schema[0]};')

        if inserts := insert_statements(connection, table):
            lines.append('')
            lines += inserts

        for kind in ('index', 'trigger', 'view'):
            if statements := object_statements(connection, kind, table):
                lines.append('')
                lines += [f'{statement};' for statement in statements]

    lines += ['', 'COMMIT;', '']
    return '\n'.join(lines)


def dump(database: Path, output: Path) -> None:
    """Write the dump, or compare it with what is on disk. Returns a process exit code."""
    with connect(database) as connection:
        rendered = render(connection)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding='utf-8', newline='\n')
    print(f'Wrote {output.relative_to(ROOT)} ({len(rendered.splitlines())} lines)')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--database', type=Path, default=DEFAULT_DATABASE, help='SQLite database to dump.')
    parser.add_argument('--output', type=Path, default=DEFAULT_DUMP, help='SQL file to write.')
    args = parser.parse_args()
    dump(args.database.resolve(), args.output.resolve())


if __name__ == '__main__':
    main()
