name: Create new FluMut release

on: 
  push:
    tags:
      - "v.*"

permissions:
  contents: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install FluMut
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run FluMut
        run: | 
          cp examples/multiple_samples.fa examples/fasta_input_example.fa
          flumut --update
          flumut -x examples/excel_output_example.xlsm examples/multiple_samples.fa

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            examples/excel_output_example.xlsm
            examples/fasta_input_example.fa
